name: scribblr
description: Scribblr app for publishing online articles
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  app_logger:
    path: packages/app_logger
  app_ui:
    path: packages/app_ui
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2
  clock: ^1.1.1
  collection: ^1.17.2
  equatable: ^2.0.5
  flow_builder: ^0.0.9
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.7
  hydrated_bloc: ^9.1.2
  intl: ^0.18.0
  json_annotation: ^4.8.1
  meta: ^1.9.1
  nb_utils: ^6.0.2
  shared_preferences: ^2.2.0
  sliver_tools: ^0.2.12
  stream_transform: ^2.1.0
  test: ^1.24.3
  video_player_platform_interface: ^6.2.0
  visibility_detector: ^0.4.0+2

dev_dependencies:
  bloc_test: ^9.1.2
  build_runner: ^2.0.3
  build_verify: ^3.0.0
  build_version: ^2.0.3
  fake_async: ^1.3.1
  flutter_test:
    sdk: flutter
  json_serializable: ^6.3.1
  mocktail: ^1.0.0
  mocktail_image_network: ^1.0.0
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
